export interface MenuIconModel {
  name: string,
  groupName: string
  value: string,
}

export const icons: MenuIconModel[] = [

  { value: 'cui-ban', name: 'ban', groupName: 'Core Ui Icons' },
  { value: 'cui-basket-loaded', name: 'basket loaded', groupName: 'Core Ui Icons' },
  { value: 'cui-bell', name: 'bell', groupName: 'Core Ui Icons' },
  { value: 'cui-bookmark', name: 'bookmark', groupName: 'Core Ui Icons' },
  { value: 'cui-briefcase', name: 'briefcase', groupName: 'Core Ui Icons' },
  { value: 'cui-brush', name: 'brush', groupName: 'Core Ui Icons' },
  { value: 'cui-calculator', name: 'calculator', groupName: 'Core Ui Icons' },
  { value: 'cui-calendar', name: 'calendar', groupName: 'Core Ui Icons' },
  { value: 'cui-cart', name: 'cart', groupName: 'Core Ui Icons' },
  { value: 'cui-chart', name: 'chart', groupName: 'Core Ui Icons' },
  { value: 'cui-check', name: 'check', groupName: 'Core Ui Icons' },
  { value: 'cui-chevron-bottom', name: 'chevron bottom', groupName: 'Core Ui Icons' },
  { value: 'cui-chevron-left', name: 'chevron left', groupName: 'Core Ui Icons' },
  { value: 'cui-chevron-right', name: 'chevron right', groupName: 'Core Ui Icons' },
  { value: 'cui-chevron-top', name: 'chevron top', groupName: 'Core Ui Icons' },
  { value: 'cui-circle-check', name: 'check (circle)', groupName: 'Core Ui Icons' },
  { value: 'cui-circle-x', name: 'x (circle)', groupName: 'Core Ui Icons' },
  { value: 'cui-cloud', name: 'cloud', groupName: 'Core Ui Icons' },
  { value: 'cui-cloud-download', name: 'cloud download', groupName: 'Core Ui Icons' },
  { value: 'cui-cloud-upload', name: 'cloud upload', groupName: 'Core Ui Icons' },
  { value: 'cui-code', name: 'code', groupName: 'Core Ui Icons' },
  { value: 'cui-cog', name: 'gear cog', groupName: 'Core Ui Icons' },
  { value: 'cui-comment-square', name: 'comment', groupName: 'Core Ui Icons' },
  { value: 'cui-credit-card', name: 'credit card', groupName: 'Core Ui Icons' },
  { value: 'cui-cursor', name: 'cursor', groupName: 'Core Ui Icons' },
  { value: 'cui-dashboard', name: 'dashboard', groupName: 'Core Ui Icons' },
  { value: 'cui-dollar', name: 'dollar', groupName: 'Core Ui Icons' },
  { value: 'cui-drop', name: 'drop', groupName: 'Core Ui Icons' },
  { value: 'cui-envelope-closed', name: 'envelope (closed)', groupName: 'Core Ui Icons' },
  { value: 'cui-envelope-letter', name: 'envelope (letter)', groupName: 'Core Ui Icons' },
  { value: 'cui-envelope-open', name: 'envelope', groupName: 'Core Ui Icons' },
  { value: 'cui-euro', name: 'euro', groupName: 'Core Ui Icons' },
  { value: 'cui-file', name: 'file', groupName: 'Core Ui Icons' },
  { value: 'cui-globe', name: 'globe', groupName: 'Core Ui Icons' },
  { value: 'cui-graph', name: 'graph', groupName: 'Core Ui Icons' },
  { value: 'cui-home', name: 'home', groupName: 'Core Ui Icons' },
  { value: 'cui-inbox', name: 'inbox', groupName: 'Core Ui Icons' },
  { value: 'cui-info', name: 'info', groupName: 'Core Ui Icons' },
  { value: 'cui-laptop', name: 'laptop', groupName: 'Core Ui Icons' },
  { value: 'cui-layers', name: 'layers', groupName: 'Core Ui Icons' },
  { value: 'cui-lightbulb', name: 'lightbulb', groupName: 'Core Ui Icons' },
  { value: 'cui-list', name: 'list', groupName: 'Core Ui Icons' },
  { value: 'cui-location-pin', name: 'location pin', groupName: 'Core Ui Icons' },
  { value: 'cui-lock-locked', name: 'lock', groupName: 'Core Ui Icons' },
  { value: 'cui-lock-unlocked', name: 'lock (unlocked)', groupName: 'Core Ui Icons' },
  { value: 'cui-magnifying-glass', name: 'magnify', groupName: 'Core Ui Icons' },
  { value: 'cui-map', name: 'map', groupName: 'Core Ui Icons' },
  { value: 'cui-monitor', name: 'monitor', groupName: 'Core Ui Icons' },
  { value: 'cui-moon', name: 'moon', groupName: 'Core Ui Icons' },
  { value: 'cui-note', name: 'note', groupName: 'Core Ui Icons' },
  { value: 'cui-paperclip', name: 'paperclip', groupName: 'Core Ui Icons' },
  { value: 'cui-pencil', name: 'pencil', groupName: 'Core Ui Icons' },
  { value: 'cui-people', name: 'people', groupName: 'Core Ui Icons' },
  { value: 'cui-phone', name: 'phone', groupName: 'Core Ui Icons' },
  { value: 'cui-pie-chart', name: 'pie chart', groupName: 'Core Ui Icons' },
  { value: 'cui-print', name: 'print', groupName: 'Core Ui Icons' },
  { value: 'cui-puzzle', name: 'puzzle', groupName: 'Core Ui Icons' },
  { value: 'cui-screen-desktop', name: 'screen desktop', groupName: 'Core Ui Icons' },
  { value: 'cui-screen-smartphone', name: 'screen smartphone', groupName: 'Core Ui Icons' },
  { value: 'cui-settings', name: 'settings', groupName: 'Core Ui Icons' },
  { value: 'cui-shield', name: 'shield', groupName: 'Core Ui Icons' },
  { value: 'cui-speech', name: 'speech', groupName: 'Core Ui Icons' },
  { value: 'cui-speedometer', name: 'speedometer', groupName: 'Core Ui Icons' },
  { value: 'cui-star', name: 'star', groupName: 'Core Ui Icons' },
  { value: 'cui-sun', name: 'sun', groupName: 'Core Ui Icons' },
  { value: 'cui-tablet', name: 'tablet', groupName: 'Core Ui Icons' },
  { value: 'cui-tags', name: 'tags', groupName: 'Core Ui Icons' },
  { value: 'cui-task', name: 'task', groupName: 'Core Ui Icons' },
  { value: 'cui-trash', name: 'trash', groupName: 'Core Ui Icons' },
  { value: 'cui-user', name: 'user', groupName: 'Core Ui Icons' },
  { value: 'cui-user-female', name: 'user (female)', groupName: 'Core Ui Icons' },
  { value: 'cui-user-follow', name: 'user (follow)', groupName: 'Core Ui Icons' },
  { value: 'cui-user-unfollow', name: 'user (unfollow)', groupName: 'Core Ui Icons' },
  { value: 'cui-wrench', name: 'wrench', groupName: 'Core Ui Icons' },

  { value: 'icon-user', name: 'icon user', groupName: 'Simple Line Icons' },
  { value: 'icon-people', name: 'icon people', groupName: 'Simple Line Icons' },
  { value: 'icon-user-female', name: 'user female', groupName: 'Simple Line Icons' },
  { value: 'icon-login', name: 'login', groupName: 'Simple Line Icons' },
  { value: 'icon-logout', name: 'logout', groupName: 'Simple Line Icons' },
  { value: 'icon-phone', name: 'phone', groupName: 'Simple Line Icons' },
  { value: 'icon-call-end', name: 'call end', groupName: 'Simple Line Icons' },
  { value: 'icon-call-in', name: 'call in', groupName: 'Simple Line Icons' },
  { value: 'icon-call-out', name: 'call out', groupName: 'Simple Line Icons' },
  { value: 'icon-map', name: 'map', groupName: 'Simple Line Icons' },
  { value: 'icon-locator-pin', name: 'locator pin', groupName: 'Simple Line Icons' },
  { value: 'icon-direction', name: 'direction', groupName: 'Simple Line Icons' },
  { value: 'icon-directions', name: 'directions', groupName: 'Simple Line Icons' },
  { value: 'icon-compass', name: 'compass', groupName: 'Simple Line Icons' },
  { value: 'icon-layers', name: 'layers', groupName: 'Simple Line Icons' },
  { value: 'icon-menu', name: 'menu', groupName: 'Simple Line Icons' },
  { value: 'icon-list', name: 'icon-list', groupName: 'Simple Line Icons' },
  { value: 'icon-options-vertical', name: 'icon-options-vertical', groupName: 'Simple Line Icons' },
  { value: 'icon-options', name: 'icon-options', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-down', name: 'arrow down', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-left', name: 'arrow left', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-right', name: 'arrow right', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-up', name: 'arrow up', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-up-circle', name: 'arrow up (circle)', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-left-circle', name: 'arrow left (circle)', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-right-circle', name: 'arrow right (circle)', groupName: 'Simple Line Icons' },
  { value: 'icon-arrow-down-circle', name: 'arrow down (circle)', groupName: 'Simple Line Icons' },
  { value: 'icon-check', name: 'check', groupName: 'Simple Line Icons' },
  { value: 'icon-clock', name: 'clock', groupName: 'Simple Line Icons' },
  { value: 'icon-plus', name: 'plus', groupName: 'Simple Line Icons' },
  { value: 'icon-close', name: 'close', groupName: 'Simple Line Icons' },
  { value: 'icon-trophy', name: 'trophy', groupName: 'Simple Line Icons' },
  { value: 'icon-screen-smartphone', name: 'smartphone (screen)', groupName: 'Simple Line Icons' },
  { value: 'icon-screen-desktop', name: 'desktop (screen)', groupName: 'Simple Line Icons' },
  { value: 'icon-plane', name: 'plane', groupName: 'Simple Line Icons' },
  { value: 'icon-notebook', name: 'notebook', groupName: 'Simple Line Icons' },
  { value: 'icon-mouse', name: 'mouse', groupName: 'Simple Line Icons' },
  { value: 'icon-magnet', name: 'magnet', groupName: 'Simple Line Icons' },
  { value: 'icon-energy', name: 'energy', groupName: 'Simple Line Icons' },
  { value: 'icon-disc', name: 'disc', groupName: 'Simple Line Icons' },
  { value: 'icon-cursor', name: 'cursor', groupName: 'Simple Line Icons' },
  { value: 'icon-chemistry', name: 'chemistry', groupName: 'Simple Line Icons' },
  { value: 'icon-speedometer', name: 'speedometer', groupName: 'Simple Line Icons' },
  { value: 'icon-shield', name: 'shield', groupName: 'Simple Line Icons' },
  { value: 'icon-screen-tablet', name: 'tablet (screen)', groupName: 'Simple Line Icons' },
  { value: 'icon-magic-wand', name: 'magic wand', groupName: 'Simple Line Icons' },
  { value: 'icon-hour-glass', name: 'hour glass', groupName: 'Simple Line Icons' },
  { value: 'icon-graduation', name: 'graduation', groupName: 'Simple Line Icons' },
  { value: 'icon-ghost', name: 'ghost', groupName: 'Simple Line Icons' },
  { value: 'icon-game-controller', name: 'game controller', groupName: 'Simple Line Icons' },
  { value: 'icon-fire', name: 'fire', groupName: 'Simple Line Icons' },
  { value: 'icon-eyeglass', name: 'eyeglass', groupName: 'Simple Line Icons' },
  { value: 'icon-envelope-open', name: 'envelope (open)', groupName: 'Simple Line Icons' },
  { value: 'icon-envelope-letter', name: 'envelope (letter)', groupName: 'Simple Line Icons' },
  { value: 'icon-bell', name: 'bell', groupName: 'Simple Line Icons' },
  { value: 'icon-badge', name: 'badge', groupName: 'Simple Line Icons' },
  { value: 'icon-anchor', name: 'anchor', groupName: 'Simple Line Icons' },
  { value: 'icon-wallet', name: 'wallet', groupName: 'Simple Line Icons' },
  { value: 'icon-vector', name: 'vector', groupName: 'Simple Line Icons' },
  { value: 'icon-speech', name: 'speech', groupName: 'Simple Line Icons' },
  { value: 'icon-puzzle', name: 'puzzle', groupName: 'Simple Line Icons' },
  { value: 'icon-printer', name: 'printer', groupName: 'Simple Line Icons' },
  { value: 'icon-present', name: 'present', groupName: 'Simple Line Icons' },
  { value: 'icon-playlist', name: 'playlist', groupName: 'Simple Line Icons' },
  { value: 'icon-pin', name: 'pin', groupName: 'Simple Line Icons' },
  { value: 'icon-picture', name: 'picture', groupName: 'Simple Line Icons' },
  { value: 'icon-handbag', name: 'handbag', groupName: 'Simple Line Icons' },
  { value: 'icon-globe-alt', name: 'globe (alt)', groupName: 'Simple Line Icons' },
  { value: 'icon-globe', name: 'globe', groupName: 'Simple Line Icons' },
  { value: 'icon-folder-alt', name: 'folder (alt)', groupName: 'Simple Line Icons' },
  { value: 'icon-folder', name: 'folder', groupName: 'Simple Line Icons' },
  { value: 'icon-film', name: 'film', groupName: 'Simple Line Icons' },
  { value: 'icon-drop', name: 'drop', groupName: 'Simple Line Icons' },
  { value: 'icon-drawer', name: 'drawer', groupName: 'Simple Line Icons' },
  { value: 'icon-docs', name: 'docs', groupName: 'Simple Line Icons' },
  { value: 'icon-doc', name: 'doc', groupName: 'Simple Line Icons' },
  { value: 'icon-diamond', name: 'diamond', groupName: 'Simple Line Icons' },
  { value: 'icon-cup', name: 'cup', groupName: 'Simple Line Icons' },
  { value: 'icon-calculator', name: 'calculator', groupName: 'Simple Line Icons' },
  { value: 'icon-bubbles', name: 'bubbles', groupName: 'Simple Line Icons' },
  { value: 'icon-briefcase', name: 'briefcase', groupName: 'Simple Line Icons' },
  { value: 'icon-book-open', name: 'book open', groupName: 'Simple Line Icons' },
  { value: 'icon-basket-loaded', name: 'basket loaded', groupName: 'Simple Line Icons' },
  { value: 'icon-basket', name: 'basket', groupName: 'Simple Line Icons' },
  { value: 'icon-bag', name: 'bag', groupName: 'Simple Line Icons' },
  { value: 'icon-wrench', name: 'wrench', groupName: 'Simple Line Icons' },
  { value: 'icon-umbrella', name: 'umbrella', groupName: 'Simple Line Icons' },
  { value: 'icon-trash', name: 'trash', groupName: 'Simple Line Icons' },
  { value: 'icon-tag', name: 'tag', groupName: 'Simple Line Icons' },
  { value: 'icon-support', name: 'support', groupName: 'Simple Line Icons' },
  { value: 'icon-share', name: 'share', groupName: 'Simple Line Icons' },
  { value: 'icon-rocket', name: 'rocket', groupName: 'Simple Line Icons' },
  { value: 'icon-question', name: 'question', groupName: 'Simple Line Icons' },
  { value: 'icon-pie-chart', name: 'pie chart', groupName: 'Simple Line Icons' },
  { value: 'icon-pencil', name: 'pencil', groupName: 'Simple Line Icons' },
  { value: 'icon-note', name: 'note', groupName: 'Simple Line Icons' },
  { value: 'icon-loop', name: 'loop', groupName: 'Simple Line Icons' },
  { value: 'icon-home', name: 'home', groupName: 'Simple Line Icons' },
  { value: 'icon-grid', name: 'grid', groupName: 'Simple Line Icons' },
  { value: 'icon-graph', name: 'graph', groupName: 'Simple Line Icons' },
  { value: 'icon-microphone', name: 'microphone', groupName: 'Simple Line Icons' },
  { value: 'icon-music-tone-alt', name: 'music tone (alt)', groupName: 'Simple Line Icons' },
  { value: 'icon-music-tone', name: 'music tone', groupName: 'Simple Line Icons' },
  { value: 'icon-earphones-alt', name: 'earphones (alt)', groupName: 'Simple Line Icons' },
  { value: 'icon-earphones', name: 'earphones', groupName: 'Simple Line Icons' },
  { value: 'icon-equalizer', name: 'equalizer', groupName: 'Simple Line Icons' },
  { value: 'icon-control-play', name: 'play', groupName: 'Simple Line Icons' },
  { value: 'icon-control-pause', name: 'pause', groupName: 'Simple Line Icons' },
  { value: 'icon-calendar', name: 'calendar', groupName: 'Simple Line Icons' },
  { value: 'icon-bulb', name: 'bulb', groupName: 'Simple Line Icons' },
  { value: 'icon-chart', name: 'chart', groupName: 'Simple Line Icons' },
  { value: 'icon-ban', name: 'ban', groupName: 'Simple Line Icons' },
  { value: 'icon-bubble', name: 'bubble', groupName: 'Simple Line Icons' },
  { value: 'icon-camera', name: 'camera', groupName: 'Simple Line Icons' },
  { value: 'icon-cloud-download', name: 'cloud download', groupName: 'Simple Line Icons' },
  { value: 'icon-cloud-upload', name: 'cloud upload', groupName: 'Simple Line Icons' },
  { value: 'icon-envelope', name: 'envelope', groupName: 'Simple Line Icons' },
  { value: 'icon-eye', name: 'eye', groupName: 'Simple Line Icons' },
  { value: 'icon-flag', name: 'flag', groupName: 'Simple Line Icons' },
  { value: 'icon-heart', name: 'heart', groupName: 'Simple Line Icons' },
  { value: 'icon-info', name: 'info', groupName: 'Simple Line Icons' },
  { value: 'icon-key', name: 'key', groupName: 'Simple Line Icons' },
  { value: 'icon-lock', name: 'lock', groupName: 'Simple Line Icons' },
  { value: 'icon-lock-open', name: 'lock (open)', groupName: 'Simple Line Icons' },
  { value: 'icon-magnifier', name: 'magnifier', groupName: 'Simple Line Icons' },
  { value: 'icon-paper-clip', name: 'paper clip', groupName: 'Simple Line Icons' },
  { value: 'icon-paper-plane', name: 'paper plane', groupName: 'Simple Line Icons' },
  { value: 'icon-power', name: 'power', groupName: 'Simple Line Icons' },
  { value: 'icon-refresh', name: 'refresh', groupName: 'Simple Line Icons' },
  { value: 'icon-reload', name: 'reload', groupName: 'Simple Line Icons' },
  { value: 'icon-settings', name: 'settings', groupName: 'Simple Line Icons' },
  { value: 'icon-star', name: 'star', groupName: 'Simple Line Icons' },
  { value: 'icon-target', name: 'target', groupName: 'Simple Line Icons' },
  { value: 'icon-credit-card', name: 'credit card', groupName: 'Simple Line Icons' },
];
