export interface MenuIconModel {
  name: string,
  value: string
}

export const icons: MenuIconModel[] = [
  { value: 'icon-user', name: 'icon-user' },
  { value: 'icon-people', name: 'icon-people' },
  { value: 'icon-user-female', name: 'icon-user-female' },
  { value: 'icon-phone', name: 'icon-phone' },
  { value: 'icon-login', name: 'icon-login' },
  { value: 'icon-logout', name: 'icon-logout' },
  { value: 'icon-menu', name: 'icon-menu' },
  { value: 'icon-list', name: 'icon-list' },
  { value: 'icon-options-vertical', name: 'icon-options-vertical' },
  { value: 'icon-options', name: 'icon-options' },
  { value: 'icon-cursor', name: 'icon-cursor' },
  { value: 'icon-speedometer', name: 'icon-speedometer' },
  { value: 'icon-shield', name: 'icon-shield' },
  { value: 'icon-screen-desktop', name: 'icon-screen-desktop' },
  { value: 'icon-envelope-open', name: 'icon-envelope-open' },
  { value: 'icon-wallet', name: 'icon-wallet' },
  { value: 'icon-speech', name: 'icon-speech' },
  { value: 'icon-puzzle', name: 'icon-puzzle' },
  { value: 'icon-printer', name: 'icon-printer' },
  { value: 'icon-credit-card', name: 'icon-credit-card' },
  { value: 'icon-star', name: 'icon-star' },
  { value: 'icon-settings', name: 'icon-settings' },
  { value: 'icon-power', name: 'icon-power' },
  { value: 'icon-magnifier-add', name: 'icon-magnifier-add' },
  { value: 'icon-link', name: 'icon-link' },
  { value: 'icon-cloud-download', name: 'icon-cloud-download' },
  { value: 'icon-paper-plane', name: 'icon-paper-plane' },
  { value: 'icon-grid', name: 'icon-grid' },
  { value: 'icon-home', name: 'icon-home' },
  { value: 'icon-pencil', name: 'icon-pencil' },
  { value: 'icon-rocket', name: 'icon-rocket' },
  { value: 'icon-share', name: 'icon-share' },
];
